on:
  push:
    paths-ignore:
      - 'packages/**'
      - 'index.yaml'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'packages/**'
      - 'index.yaml'
      - '**.md'

env:
  HELM_VERSION: 3.9.2

jobs:
  install-chart:
    name: Install chart
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        chart:
          - victoria-metrics-agent
          - victoria-metrics-alert
          - victoria-metrics-anomaly
          - victoria-metrics-auth
          - victoria-metrics-cluster
          - victoria-metrics-gateway
          - victoria-metrics-k8s-stack
          - victoria-metrics-operator
          - victoria-metrics-single
        k8s_version: ["v1.22.12", "v1.24.3", "v1.23.8"]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            helmv3
            kubectl
          helm: "${{ env.HELM_VERSION }}"
          kubectl: "${{ matrix.k8s_version }}"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Create k3d cluster
        uses: nolar/setup-k3d-k3s@v1
        with:
          version: ${{ matrix.k8s_version }}

      - name: Remove node taints
        run: |
          kubectl taint --all=true nodes node.cloudprovider.kubernetes.io/uninitialized- || true

      - name: Run chart-testing (install)
        run: ct install --config .github/ci/ct.yaml --charts "charts/${{ matrix.chart }}"
